# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup .NET Tools
      run: dotnet tool install --global dotnet-ef
      
    - name: Install frontend dependencies
      working-directory: ./ptuswph-frontend
      run: npm ci
      
    - name: Build frontend
      working-directory: ./ptuswph-frontend
      run: npm run build
      
    - name: Restore backend dependencies
      working-directory: ./ptuswph-backend
      run: dotnet restore
      
    - name: Migrate
      working-directory: ./ptuswph-backend
      run: dotnet ef database update
      
    - name: Build
      working-directory: ./ptuswph-backend
      run: dotnet build --no-restore --configuration Release --output ../app
      
    - name: Check back
      run: ls ./app
      
    - name: Check wwwroot
      run: ls ./ptuswph-backend/wwwroot
      
    - name: Check database
      run: ls ./ptuswph-backend/Database

